<a href="https://colab.research.google.com/github/Rubal-code/DEEP-LEARNING/blob/main/1_quantization_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy matplotlib

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(-1,1,100)
x[:10]

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182])

In [3]:
# define the quantization parameters
min_x = -1.0
max_x = 1.0
qmin = -128
qmax = 127

# calculate scale
scale = (max_x - min_x) / (qmax - qmin)

scale

0.00784313725490196

In [4]:
zero_point = 0
#quantization
q = np.round((x - zero_point) / scale).astype(int)

q=np.clip(q,qmin,qmax)

q[:10]

array([-128, -125, -122, -120, -117, -115, -112, -109, -107, -104])

In [5]:
# dequantization
x_hat=scale * (q - zero_point)
x_hat[:10]

array([-1.00392157, -0.98039216, -0.95686275, -0.94117647, -0.91764706,
       -0.90196078, -0.87843137, -0.85490196, -0.83921569, -0.81568627])

#(NF4)Normal float 4 quantization

In [10]:
#step 1 define the 16 nf4 values
nf4_values=np.array([
    -1,-0.75,-0.5,-0.35,-0.2,-0.1,-0.05,-0.01,
    0.01,0.05,0.1,0.2,0.35,0.5,0.75,1
])
# simulate the original float values
x=np.linspace(-1,1,100)
x[:10]

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182])

In [12]:
# step 3 : quantize the x by mapping to nearest nf4 value
def quantize_to_nf4(x_vals,nf4_luft):
  indices=np.argmin(np.abs(x_vals[:,None] - nf4_luft[None,:]),axis=1)
  return nf4_luft[indices]

q=quantize_to_nf4(x,nf4_values)
q[:10]

array([-1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -0.75, -0.75,
       -0.75])