In [3]:
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


reviews=[
        'nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement'
]
sentiments=np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot("amazing restaurant",30)     # 0-->29

[20, 27]

In [6]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[15, 17],
 [20, 27],
 [16, 2],
 [13, 26, 10],
 [6, 24, 9],
 [15, 17],
 [6, 24, 4],
 [4, 14],
 [4, 14],
 [1, 23]]

In [7]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[15 17  0  0]
 [20 27  0  0]
 [16  2  0  0]
 [13 26 10  0]
 [ 6 24  9  0]
 [15 17  0  0]
 [ 6 24  4  0]
 [ 4 14  0  0]
 [ 4 14  0  0]
 [ 1 23  0  0]]


In [11]:
embeded_vector_size=5  # Each word will be represented by 5 numbers (a vector of size 5).
model=Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding_layer'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

'''

Text Sentence
      ↓
Tokenization
      ↓
Word Index Numbers
      ↓
Embedding Layer
(words → vectors)
      ↓
Flatten Layer
(2D → 1D)
      ↓
Dense Layer
      ↓
Sigmoid Output
(0 or 1) 

'''

'\n\nText Sentence\n      ↓\nTokenization\n      ↓\nWord Index Numbers\n      ↓\nEmbedding Layer\n(words → vectors)\n      ↓\nFlatten Layer\n(2D → 1D)\n      ↓\nDense Layer\n      ↓\nSigmoid Output\n(0 or 1) \n\n'

In [12]:
X=padded_reviews
y=sentiments


In [13]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_layer (Embedding  (None, 4, 5)              150       
 )                                                               
                                                                 
 flatten_2 (Flatten)         (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
model.fit(X, y, epochs=5, verbose=0)

In [15]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 319ms/step - loss: 0.6869 - accuracy: 0.6000


0.6000000238418579

In [17]:
weights=model.get_layer('embedding_layer').get_weights()[0]
len(weights)

30

In [18]:
weights[4]

array([ 0.0185871 , -0.03411806, -0.02223967, -0.01367726, -0.04051567],
      dtype=float32)