In [1]:
import tensorflow as tf


In [2]:
daily_sales_numbers=[21,22,-108,31,32,-109,33,34,-110,35,36,-111,37,38,-112,39,40,-113]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers) # Create a TensorFlow dataset from the daily sales numbers which means we are converting the list of daily sales numbers into a format that TensorFlow can work with for further processing and analysis.
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset.as_numpy_iterator():# Iterate through the TensorFlow dataset using as_numpy_iterator() to convert each element of the dataset into a NumPy array format, which allows us to easily access and manipulate the individual sales numbers.
    print(sales)

21
22
-108
31
32
-109
33
34
-110
35
36
-111
37
38
-112
39
40
-113


In [5]:
tf_dataset=tf_dataset.filter(lambda x:x>0) # Filter the dataset to include only positive sales numbers, which means we are removing any negative sales numbers from the dataset, leaving us with only the valid sales data for further analysis.
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
33
34
35
36
37
38
39
40


In [6]:
tf_dataset=tf_dataset.map(lambda x: x*10) # Map the dataset to multiply each sales number by 10, which means we are scaling the sales numbers by a factor of 10, potentially for normalization or to adjust the scale of the data for further analysis or modeling.
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

210
220
310
320
330
340
350
360
370
380
390
400


In [7]:
tf_dataset=tf_dataset.shuffle(3) # Shuffle the dataset with a buffer size of 3, which means we are randomly shuffling the order of the sales numbers in the dataset using a buffer of 3 elements, helping to ensure that the data is not in a specific order and can improve the performance of machine learning models trained on this data.
for sales in tf_dataset.as_numpy_iterator():    
    print(sales)

210
220
330
310
350
320
360
380
390
370
400
340


In [8]:
for sales_batch in tf_dataset.batch(3): # Batch the dataset with a batch size of 3, which means we are grouping the sales numbers into batches of 3 for more efficient processing and training of machine learning models, allowing us to work with multiple data points at once.
    print(sales_batch)

tf.Tensor([310 210 320], shape=(3,), dtype=int32)
tf.Tensor([330 220 360], shape=(3,), dtype=int32)
tf.Tensor([350 370 340], shape=(3,), dtype=int32)
tf.Tensor([400 380 390], shape=(3,), dtype=int32)


##### alll these steps in the single line


In [9]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y: y*10).shuffle(3).batch(3) # Chain multiple transformations together to create a more complex data processing pipeline, which means we are applying multiple operations (filtering, mapping, shuffling, and batching) in a single line of code to efficiently process the sales data for machine learning tasks.
for sales_batch in tf_dataset.as_numpy_iterator():
    print(sales_batch)

[310 320 330]
[340 220 360]
[370 350 380]
[210 400 390]


# images

In [12]:
images_ds=tf.data.Dataset.list_files('images/*/*',shuffle=False)

In [13]:
image_count = len(images_ds)
image_count

130

In [14]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [15]:
for files in images_ds.take(5):
    print(files)

tf.Tensor(b'images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg', shape=(), dtype=string)
tf.Tensor(b'images\\cat\\7 Foods Your Cat Can_t Eat.jpg', shape=(), dtype=string)
tf.Tensor(b'images\\cat\\A cat appears to have caught the....jpg', shape=(), dtype=string)
tf.Tensor(b'images\\cat\\Adopt-A-Cat Month\xc2\xae - American Humane....jpg', shape=(), dtype=string)
tf.Tensor(b'images\\cat\\All About Your Cat_s Tongue.jpg', shape=(), dtype=string)


In [17]:
images_ds=images_ds.shuffle(200)
for files in images_ds.take(5):
    print(files.numpy())

b'images\\dog\\Top 10 Smartest Dog Breeds - Most....jpg'
b'images\\dog\\25 Best Small Dog Breeds \xe2\x80\x94 Cute and....jpg'
b'images\\cat\\What to do if your cat is marking....jpg'
b'images\\cat\\Thinking of getting a cat....png'
b'images\\cat\\All About Your Cat_s Tongue.jpg'


In [18]:
class_names=['cat','dog']


In [20]:
train_size=int(image_count*0.8)
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [21]:
len(train_ds),len(test_ds)

(104, 26)

In [22]:
import os
def get_label(file_path):
    # split the path into the segments
    parts=tf.strings.split(file_path,os.path.sep)
    # grab the parent folder name
    return parts[-2]

In [23]:
get_label("images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [24]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [25]:
img, label = process_image("images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg")
img.numpy()[:2]

array([[[155.      , 186.      , 215.      ],
        [156.      , 187.      , 216.      ],
        [158.      , 189.      , 218.      ],
        [160.0039  , 189.0039  , 219.0039  ],
        [161.0039  , 190.0039  , 220.0039  ],
        [162.      , 191.      , 221.      ],
        [166.      , 193.      , 222.      ],
        [167.      , 194.      , 223.      ],
        [168.      , 195.      , 224.      ],
        [169.      , 196.      , 225.      ],
        [170.      , 197.      , 224.      ],
        [170.0039  , 197.0039  , 224.0039  ],
        [172.      , 199.      , 226.      ],
        [173.0039  , 199.0039  , 224.0039  ],
        [174.0039  , 200.0039  , 225.0039  ],
        [175.0039  , 201.0039  , 226.0039  ],
        [176.      , 202.      , 227.      ],
        [177.0039  , 203.0039  , 228.0039  ],
        [177.0039  , 203.0039  , 228.0039  ],
        [179.0039  , 203.0039  , 227.0039  ],
        [180.0039  , 204.0039  , 228.0039  ],
        [180.0039  , 204.0039  , 2

In [26]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [27]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  ...
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]]

 [[  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  ...
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]]

 [[  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  ...
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]
  [  0.  28.  91. 255.]]

 ...

 [[186. 228. 255. 255.]
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]
  ...
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]]

 [[186. 228. 255. 255.]
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]
  ...
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]]

 [[186. 228. 255. 255.]
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]
  ...
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]
  [186. 228. 255. 255.]]], shape=(128, 128, 4), dtype=float32)
**** tf.Tensor(b'dog', shape=

In [28]:
def scale(image, label):
    return image/255, label

In [29]:
train_ds = train_ds.map(scale)

In [30]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.8019167 0.8019167 0.8019167]
****Label:  b'cat'
****Image:  [0.90226716 0.22889093 0.02723652]
****Label:  b'cat'
****Image:  [0.82817096 0.8203278  0.7693474 ]
****Label:  b'cat'
****Image:  [0.878508   0.8745864  0.21576287]
****Label:  b'dog'
****Image:  [0.9529412  0.9607843  0.95686275]
****Label:  b'dog'
