In [1]:
import numpy as np


In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# implement mean absoulte error


In [3]:
def mae(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("Total error:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_true,y_predicted)

Total error: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

Implement same thing using numpy in much easier way

In [5]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [6]:
mae_np(y_true,y_predicted)

np.float64(0.5)

# Implement Log Loss or Binary Cross Entropy

In [7]:
np.log([0])

C:\Users\hp\AppData\Local\Temp\ipykernel_2088\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [8]:
epsilon = 1e-15

In [9]:
np.log([epsilon])

array([-34.53877639])

In [10]:
y_predicted

array([1, 1, 0, 0, 1])

In [11]:
y_predicted_new=[max(epsilon,i) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [12]:
1-epsilon

0.999999999999999

In [13]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [14]:
y_predicted_new = np.array(y_predicted_new)

In [15]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [16]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [17]:

def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [18]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

# mse

In [19]:
def mse(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=(yt-yp)**2
    print("Total error:",total_error)
    mse = total_error/len(y_predicted)
    print("Mean squared error is:",mse)
    return mse

In [20]:
mse(y_true,y_predicted)

Total error: 1.83
Mean squared error is: 0.366


np.float64(0.366)

In [21]:
np.mean(np.square(y_true-y_predicted))

np.float64(0.366)

In [22]:
np.sum(np.square(y_true-y_predicted))

np.float64(1.83)